---
title: "Gentle Introduction to Programming Part 2"
subtitle: ": GIS with Geopandas"
date: 04/22/2024
date-format: long
author:
  - name: Hyesop Shin
    orcid: 0000-0003-2637-7933
    email: hyesop.shin@auckland.ac.nz
    affiliations:
      - name: University of Auckland
        address: 23 Symonds Street
        city: Auckland
        postal-code: 1010
format: 
  revealjs:
      logo: Figs/uoa-logo.png
      css: logo.css
      slide-number: true
      show-slide-number: print
editor: source
include-in-header:
  - text: |
      <style type="text/css">
      ul li ul li {
        font-size: 0.7em;
      }
      </style>
---

## What will we cover today?

-   How to import spreadsheet data
-   How to clean and explore data
-   Data Visualisation
-   How to play with GIS data

::: notes
:::

## Recap of Previous Lecture

-   Maths
-   How to assign variables, lists
-   For loops
-   Conditional statements
-   How to call packages using `import` (tidy bit)


## Getting started with Pandas




## Getting Started with GeoPandas
* Objective: Familiarize students with GeoPandas and its uses in spatial data analysis.
* Topics Covered:
* Installation of GeoPandas.
* Basic data structures in GeoPandas: GeoSeries and GeoDataFrame.
* Reading and writing spatial data.

## Working with Geospatial Data
Objective: Teach how to manipulate and process geospatial data using GeoPandas.
Topics Covered:
Loading spatial data from different formats (Shapefile, GeoJSON, etc.).
Basic data manipulation (selecting, filtering, and sorting data).
Coordinate reference systems: understanding and transforming.

## Spatial Analysis Basics
Objective: Introduce basic spatial analysis techniques.
Topics Covered:
Spatial joins and merging data.
Calculating distances and nearest neighbor analysis.
Basic spatial queries and operations (buffer, intersect, union).

## Visualisation with GeoPandas
Objective: Teach students how to visualise spatial data effectively.
Topics Covered:
Plotting with GeoPandas.
Customizing plots (color, size, legend, etc.).
Integrating with other libraries like Matplotlib and Plotly for enhanced visualizations.




## <br> Thanks! <br> Q & A {style="text-align: center;"}
